### ISSUE TITLE
Error executing process > 'normalize_reads', RAM required 150GB

### ISSUE THREAD

**Issue by jcoludar** [PalMuc/TransPi#13]
Greetings! I tried running a docker version of TransPi on my transcriptomic data and after a seemingly successful start it failed during "normalize reads" process. Seemingly it wants to have 150GB worth of RAM (I only have 125, which I always thought would be more than enough). Is there a work-around or am I doing something wrong?

The code I used to run it:

`sudo ./nextflow run TransPi.nf --all --maxReadLen 150 --k 25,35,55,75,85     --reads '/media/jcoludar/Daten/Ivan/02_Transcri/Transcriptomes/T5_09_Po_do_VG2/*_R[1,2].fastq.gz' --outdir Results_Polistes     -profile docker,TransPiContainer`

**The Error message**

> Error executing process > 'normalize_reads (09-Po-du-VG2)'
> 
> Caused by:
>   Process requirement exceed available memory -- req: 150 GB; avail: 125.8 GB
> 
> Command executed:
> 
>   echo 09-Po-du-VG2
>   
>   echo -e "\n-- Starting Normalization --\n"
>   
>   mem=$( echo 150 GB | cut -f 1 -d " " )
>   
>   insilico_read_normalization.pl --seqType fq -JM ${mem}G --max_cov 100 --min_cov 1 --left left-09-Po-du-VG2.filter.fq --right right-09-Po-du-VG2.filter.fq --pairs_together --PARALLEL_STATS --CPU 15
>   
>   echo -e "\n-- DONE with Normalization --\n"
>   
>   cat .command.out | grep "stats_file" -A 3 | tail -n 3 >09-Po-du-VG2_normStats.txt
>   
>   cp left.norm.fq left-"09-Po-du-VG2".norm.fq
>   cp right.norm.fq right-"09-Po-du-VG2".norm.fq
>   
>   mv left.norm.fq 09-Po-du-VG2_norm.R1.fq
>   mv right.norm.fq 09-Po-du-VG2_norm.R2.fq
>   
>   pigz --best --force -p 15 -r 09-Po-du-VG2_norm.R1.fq
>   pigz --best --force -p 15 -r 09-Po-du-VG2_norm.R2.fq
> 
> Command exit status:
> 
> Command output:
>   (empty)
> 
> Work dir:
>   /media/jcoludar/Daten/Ivan/Software/TransPi/TransPi/work/b3/b323002917226824e319cadb1441f5
> 
> Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by rivera10** [comment]
Hello @jcoludar, 

In the `nextflow.config` you need to specify the RAM and CPUs of your system. Currently, that step has a value of 150Gb of RAM. See [here](https://palmuc.github.io/TransPi/#_resources) for more info. After you change the values to the ones of your system then you can use the `-resume` option of nextflow.

Anything let me know. 

Best, 
Ramon

**Comment by jcoludar** [comment]
Hello @rivera10,

Thanks for the reply and sorry, it is my bad for not reading the manual attentively. It worked, but only through normalize read step, sadly. It then got stuck with
`WARN: Access to undefined parameter `avg_ins` -- Initialise it to a default value eg. `params.avg_ins = some_value``
I checked and nextflow.config does have it defined to default 200. Am I missing something again? Sorry if that's the case, but I did not find anything about it in the manual.

Cheers,
Ivan

**Comment by rivera10** [comment]
Hello, 

You can omit that warning. In the case you know the insert size of the library you can have it there. Otherwise, it will print that warning to you but the program will continue working.

Best,
Ramon

**Comment by rivera10** [comment]
Hello. I have not seen that warning before. Are you using conda or containers?

If you are using containers then the creation of the sqlite sometimes can cause problems if you do not have all the perl dependencies needed. One quick solution will be to create a conda env to install the sqlite database using Trinotate. 
```
conda create -n trinotate -c bioconda trinotate=3.2.1=pl526_0
conda activate trinotate
Build_Trinotate_Boilerplate_SQLite_db.pl Trinotate
```

**Comment by rivera10** [comment]
Hello @jcoludar,

Did you manage to solve the problem? I will close this issue for now. If you still have problems feel free to open it again. 

I also did several changes to the script to solve other issues. I will suggest to pull again the repository so you have all the updates. 

Anything let us know.

Best,
Ramon
