### ISSUE TITLE
precheck issues

### ISSUE THREAD

**Issue by rsuchecki** [PalMuc/TransPi#14]
The pipeline looks really promising but I am having difficulty with the setup.

```sh
bash precheck_TransPi.sh $PWD
``` 

With either `yes` or `no` to singularity/docker, followed by 

```
2) EUKARYOTA
4) Plants_(Kingdom) 
7) Poales_(Order)
```

Successfully downloads BUSCO V4 DB,

```
         -- Preparing files ... --


         -- DONE with BUSCO V4 database --


         -- No BUSCO V3 available for poales --
```

BUSCO v3 are not available and `nextflow.config` is not generated from the template.

What is the reasoning for requiring both versions of BUSCO databases? Would v4 not be sufficient?

**Comment by rivera10** [comment]
Hello @rsuchecki,

When we were developing the pipeline the transition of BUSCO v3 to v4 was happening so we decided to use both. However, for the next release, we are dropping BUSCO v3 and only working with v4. Also, there is v5 already out and we are testing it at the moment to incorporate it in future releases. I already made the changes for using only the BUSCO v4 in the dev branch of TransPi. Merging to the master branch will happen soon. In the meantime, you can change to the dev branch and run the tool. Let me know if you need further assistance.

Best,
Ramon

**Comment by rsuchecki** [comment]
Thank you @rivera10 - I checked-out dev and pipeline is up and running now! 👍

**Comment by rivera10** [comment]
Great. Anything let us know.
