### ISSUE TITLE
no perl in cointainer

### ISSUE THREAD

**Issue by rsuchecki** [PalMuc/TransPi#15]
It appears that the mulled container 
`https://depot.galaxyproject.org/singularity/mulled-v2-962eae98c9ff8d5b31e1df7e41a355a99e1152c4:5aac6d1d2253d47aee81f01cc070a17664c86f07-0` 
lacks perl interpreter required by the `evigene` process:

```
Command output:
  
  -- Starting EviGene --

Command error:
  .command.sh: /path/redacted/TransPi/scripts/evigene/scripts/prot/tr2aacds.pl: /usr/bin/perl: bad interpreter: No such file or directory
```

**Comment by rivera10** [comment]
I'll check and work on a solution for that. Thanks for letting us know.

**Comment by rivera10** [comment]
I submitted a change to the mulled container. See [here](https://github.com/BioContainers/multi-package-containers/pull/1727)

**Comment by rsuchecki** [comment]
Great, I think the container image should become available after the PR is merged 👍

**Comment by rivera10** [comment]
Still waiting for the mulled container. Issue was closed in the PR of the new version

**Comment by rivera10** [comment]
Mulled container info was added. Anything let me know.
