### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by kazumaxneo** [PalMuc/TransPi#18]
It is a great tool and I would love to use it for my RNA seq.
However, when I download and run the database, it quits with the following error immediately after starting.

$ nextflow run TransPi.nf --onlyAsm --reads '/media/kazu/8TB2/TransPi/quality_trimmed_R[1,2].fastq.gz' --k 41,53 --maxReadLen 84 -profile conda
N E X T F L O W  ~  version 20.07.1
Launching `TransPi.nf` [sharp_lorenz] - revision: 6acd9a7ecd
Script compilation error
- file : /media/kazu/8TB2/TransPi/TransPi.nf
- cause: expecting '}', found ',' @ line 2876, column 35.
                       file(assembly), file(annotation) from

nextflow version is 20.07.1.5412

**Comment by rivera10** [comment]
Hello @kazumaxneo 

I did a test run and for me is working fine. Also I asked a colleague and he told me that he has no issues. I will suggest to `git pull` just in case you have an old version of the tool. Let me know if the problem continues.

Best,
Ramon

**Comment by kazumaxneo** [comment]
Hi Ramon,

Thanks for your response. 
Sees to be a problem with my nextflow version.
I updated nextflow to the latest version, and it now runs perfectly.
Thank you for teaching me so kindly.

**Comment by rivera10** [comment]
I'll close this issue. If you need further help let us know.
