### ISSUE TITLE
Java issue

### ISSUE THREAD

**Issue by brittonstrickland** [PalMuc/TransPi#20]
Hi all,

Excited to get this pipeline started. The installation via Conda and the precheck worked great. I'm currently trying to run some data through the pipeline, but there seems to be an issue when pointing to my java installation.

By running:

`/nextflow  run TransPi.nf --all --reads '~Desktop/RNAseq/*_R[1,2].fastq.gz' --k 25,41,53 --maxReadLen 80 -profile conda`

I made sure I have java set in my path:
`export JAVA_HOME=$(/usr/libexec/java_home)`

Running the transpi command, I get the following error:

> ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 or later is installed
> NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
>  JAVA_CMD: /Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home/bin/java
>  JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home

I tried a few troubleshooting items online but no success. Any thoughts? Thanks for your help.

**Comment by rivera10** [comment]
Hello @brittonstrickland,

What do you have as output when running `java -version` and `nextflow -version`?

I am not sure what is the problem but I can help you to figure it out. Let me know

Best,
Ramon

**Comment by brittonstrickland** [comment]
Java
> Brittons-MBP:~ brittonstrickland$ java -version
> openjdk version "11.0.9.1" 2020-11-04 LTS
> OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
> OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)


Nextflow
> Brittons-MBP:~ brittonstrickland$ /Users/brittonstrickland/Desktop/TransPi/nextflow -version
> ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 or later is installed
> NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
>  JAVA_CMD: /Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home/bin/java
>  JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk-16.0.2.jdk/Contents/Home

Thanks!

**Comment by rivera10** [comment]
I found this https://github.com/nextflow-io/nextflow/issues/2057.

You can either use JVM up to 15 or use the edge version of nextflow `21.05.0-edge`. This version should work with JDK 16 (https://github.com/nextflow-io/nextflow/commit/caace1c5b26ad878091a8d4afcc6dd338fbdf985).  

To use the edge version use `export NXF_VER=21.05.0-edge && curl -s https://get.nextflow.io | bash`

Let me know if this solves the issue

**Comment by brittonstrickland** [comment]
Yes that fixed it! Thanks for your help.

**Comment by rivera10** [comment]
No worries. Anything let us know.
