### ISSUE TITLE
Installation Issue (file yml?)

### ISSUE THREAD

**Issue by francesconardi** [PalMuc/TransPi#28]
Dear Author,
we are trying - with little success - to install TransPi (conda option) but it seems not to create any environment, not even the referenced TransPi environment. 
First question is whether your recent update is complete or you are still working on it - suggesting the opportunity to wait a while before trying this new version.

A couple of possible issues while trying to go through the initial lines of your precheck script:
- at the beginning, the script checks whether conda version is higher than 4.8 (variable $vern). We have 4.10, and the condition is not satisfied. In other words, 4.8 is seen as higher than 4.10 (and numerically it is).
- the script seems to look for a transpi_env.yml in the github cloned folder, but there is none. Should the file be acquired from an alternative source?

Thanks a lot for this useful piece of software, that we are eager to see running on our computers,
Regards.

**Comment by francesconardi** [comment]
Dear Ramon,
I am slowly working my way with the installation, manually completing some steps that fail in automatic.
Creation of some conda envs failed, and I could rescue the process by issuing the create environment command manually and then resuming the run.

I am now at the rnaquast env, whose install command is:
conda create --mkdir --yes --quiet --prefix /home/u3601/prog/TransPi_folder/condaEnv/env-fa8b0a403402a49160ee9bce39b0a3c5 -c conda-forge bioconda::rnaquast=2.0.1=0

The command fails both when issued in the context of the nextflow pipeline (it trows an error) and ALSO if I issue the command manually (unlilke other envs).

Can you suggest a workaround to install rnaquast env, possibly in the same env structure created by TransPi?

Thanks
Francesco Nardi

**Comment by rivera10** [comment]
Hello @francesconardi,

Sometimes there are issues with conda packages if you already have them. One thing you can try is to use the `conda clean --all` to erase all packages and info of conda. Then start again the pipeline. Let me know if that works.

Best,
Ramón

**Comment by francesconardi** [comment]
Hi Ramon,

I have succesfully cloned the rnaquast env from a different source:
conda create  --mkdir --prefix /...../condaEnv/env-fa8b0a403402a49160ee9bce39b0a3c5 -c bioconda rnaquast=2.0.1=0
and, at present, the main line of TransPi is running smootly.

I'm now after the three external packages SignalP, tmhmm and rnammer, where I get some errors.
I see that signalp expects input using a different set of options compared to what TransPi issues. I am wondering if this depends on the package version I downloaded. Before I try to edit the nextflow script accordingly, could you indicate the exact version of the three packages you are using (I'm on centos linux). This may be a simple solution.

Cheers,
and thanks for your continuing assistance,
Francesco Nardi

**Comment by rivera10** [comment]
Hello @francesconardi,

No worries at all. Thank you for pointing these issues so I can come with solutions for future updates. 

Good to hear the env was created successfully. 

For the signalP analysis I am using version 4.1.

Best,
Ramón

**Comment by francesconardi** [comment]
May I know which versions of rnammer and tmhmm you are using as well?

Thank you
Francesco Nardi

**Comment by rivera10** [comment]
RNAmmer v1.2 and TMhmm v2.0. What errors do you get?

**Comment by francesconardi** [comment]
Dear Ramon,

I am working on the integration of Rnammer, SignalIP and tmhmm with the main script, and I get a number of errors.
The one I am looking into at present arises from the script (apparently) not finding RnammerTranscriptome.pl (output below).

I actually have two copies of the script:
~/prog/TransPi_folder/scripts/RnammerTranscriptome.pl
~/prog/TransPi_folder/condaEnv/env-b96eed500b8c9d678c4cc5d666983118/bin/RnammerTranscriptome.pl

Where is TransPi looking for the aforementioned script? Where is it expected to be?

Thank you,
Francesco Nardi


(output)

Command output:

  -- Starting with RNAMMER --


  -- Done with RNAMMER --

Command error:
  .command.sh: line 7: RnammerTranscriptome.pl: command not found

**Comment by rivera10** [comment]
Hello,

You need to provide the PATH of these programs in the config file. We do this in the pipeline since each user needs a license for using the tools. Once you have the PATH in the config you should be fine https://github.com/PalMuc/TransPi/blob/146e71c19f8337c7a4cce766e83c413b907798ce/template.nextflow.config#L45-L51
