### ISSUE TITLE
precheck not installing software

### ISSUE THREAD

**Issue by hcliedtke** [PalMuc/TransPi#37]
Hi, thanks for developing this nice pipeline, it looks really promising. I am trying to follow the manual, but it seems like the precheck_TransPi.sh script is not installing any software. It seems to download all of the DBs, but when I proceed to run the full TransPi analysis, it stops almost immediately because it cannot find fastp. In fact, I don't seem to find any of the dependencies installed on my system. It is my understanding that the precheck_TransPi script should have handled that. Am I missing something? Sorry if this has been addressed elsewhere, or if I am missing something obvious.

**Comment by rivera10** [comment]
Hello @hcliedtke, 

The precheck (previous versions) was in charge of tools installation. However, that was modified to also provide the option of containers. 

Can you show me how you called the tool? Perhaps you are missing the `-profile` option and to tell TransPi what to use for tools installation: conda, singularity or docker. 

For example, to use conda add `-profile conda` when you call TransPi.

Let me know if that works.

Best,
Ramon

**Comment by hcliedtke** [comment]
Hi @rivera10. Thanks so much! that was the problem. Setting `-profile conda` resolved it.
