### ISSUE TITLE
Problem in installing 

### ISSUE THREAD

**Issue by silenus092** [PalMuc/TransPi#4]
Hi, 

Thank you for providing such a very beneficial tool

However, I try to install the program and I faced an error while I install it, I attach the screenshot 

![image](https://user-images.githubusercontent.com/8342780/108565963-eb05f900-7305-11eb-93af-b7d34b75bab4.png)

I select EUKARYOTA, and then I select Superkingdom, suddenly the program stops with the error message above.

```
    Please select database: 1
cat: ./conf/busV4list.txt: No such file or directory
cat: ./conf/busV4list.txt: No such file or directory
cat: ./conf/busV4list.txt: No such file or directory
cat: ./conf/busV3list.txt: No such file or directory

         -- No BUSCO V3 available for  --

```

Here are the commands I used so far 
```
git clone https://github.com/palmuc/TransPi.git
cd TransPi
bash precheck_TransPi.sh .
```

**Comment by rivera10** [comment]
Hello,

To solve this use the `PATH` instead of `.`

Example:
```
bash precheck_TransPi.sh /home/ubuntu/TransPi
``` 

I'll try to find a way how to solve this for future updates. 

Thanks

**Comment by silenus092** [comment]
Thank you I now made it runnable, btw I have a small question 
How to select Kmers number?
 I saw the list of number in GitHub doc. or in your paper  for example ;
`--k 25,41,53 --maxReadLen 75` 

However, still, I do not fully understand how to related these number to the sequence length

**Comment by rivera10** [comment]
Selection of kmers is based on your read length. However, no matter the length, try to have a combination of "short" and "long" kmers. Short kmers generate more transcripts (but with more errors), and long kmers generate less transcripts (but with less misassemblies). For 50bp I often used `--k 25,33,37`. I have colleagues that tried different combinations (e.g. 25,33,39) and the results do not change much because we are using a multi assembler approach.

**Comment by Guarup** [comment]
The tool looks excellent, I would like to implement it in my analysis: I followed the installation tutorial, including the installation of the metazoa database, I got the following:
bin         docs             precheck_TransPi.sh  template.nextflow.config
conf        LICENSE          README.md            transpi_env.yml
DBs         nextflow         remove_failed.sh     TransPi.nf
Dockerfile  nextflow.config  scripts              update_databases.sh
And when running the script with the location of my samples:
nextflow run TransPi.nf --all --maxReadLen 150 --k 25,35,55,75 --reads /PATH/filter_samples/*_R[1,2].fastq.gz -profile conda --myConda
The following error was reported:
nextflow: command not found
I would be grateful if you could please guide me in resolving the problem.

**Comment by rivera10** [comment]
Hello @Guarup,

Did you use the precheck script? It looks like you are missing `nextflow` program. I'll suggest to run the precheck again to make sure all the requirements are installed.  Let me know how it goes. 

Best,
Ramon

**Comment by rivera10** [comment]
Also, it could be that you have nextflow installed locally in the directory (done with the precheck) and need to add the `./` before the name to execute the program (e.g `./nextflow ...`).
