### ISSUE TITLE
Fail to download uniprot_metazoa_33208.fasta 

### ISSUE THREAD

**Issue by dppss90008** [PalMuc/TransPi#56]
Dear author 

I found the following error, when i ran the test command 
 ./nextflow run TransPi.nf --all -profile docker,test --outdir Results_test

![image](https://github.com/PalMuc/TransPi/assets/34399929/adce4ea7-05c5-466b-8134-1ad3a740311b)

the raising error showed that uniprot_metazoa_33208.fasta is missing.

I traced back to the database, and found the following error.
The error may due to the api changes in uniprot database, when I ran precheck_TransPi.sh
![image](https://github.com/PalMuc/TransPi/assets/34399929/5f844be7-4f32-4e26-9f29-0021d31637c0)

hope you can help with this issue.

**Comment by sevragorgia** [comment]
Dear dppss90008,

please check [issue #52](https://github.com/PalMuc/TransPi/issues/52)

the rest api changed and you have to use a legacy option. The instructions to solve this issue can be found there (in issue #52)

cheers

Sergio

**Comment by dppss90008** [comment]
Dear Sergio,

I tried replacing the old URL with "https://legacy.uniprot.org/uniprot/?query=taxonomy:33208&format=fasta&compress=yes&include=no". 

But it still not work. It seems that the URL you provided is no longer valid.

CH

**Comment by sevragorgia** [comment]
Hmm, I was afraid this will be case at some point but not now :-(

I will try to figure out how to do it now but I may need some time. Will post it back here.

Sergio

**Comment by sevragorgia** [comment]
I drafted a possible solution in issue #52. Please report if it worked.
