### ISSUE TITLE
Trans-ABySS assembly error

### ISSUE THREAD

**Issue by juadiegaitan** [PalMuc/TransPi#6]
Hi Ramon
Super cool pipeline!
I wonder if you had any issues with the Trans-ABySS assemblies. I am getting errors for that step when running it. Basically the pipeline kills/finish the step. There is no major information in the log file, just that the single attempt and the end of the run for that step.
Thoughts about this?
Thanks for the feedback!
Best
Juan

Log

echo -e "\n-- Starting Trans-ABySS assemblies --\n"

for x in `echo 25,35,55,75,85 | tr "," " "`;do
    echo -e "\n-- Trans-ABySS k${x} --\n"
    transabyss -k ${x} --pe left-S69L.norm.fq right-S69L.norm.fq --outdir S69L_transabyss_${x} --name k${x}.transabyss.fa --threads 15 -c 12 --length 200
done

echo -e "\n-- Finished with the assemblies --\n"

for x in `echo 25,35,55,75,85 | tr "," " "`;do
    sed -i "s/>/>TransABySS.k${x}./g" S69L_transabyss_${x}/k${x}.transabyss.fa-final.fa
done

cat S69L_transabyss_*/k*.transabyss.fa-final.fa >S69L.TransABySS.fa

for x in `echo 25,35,55,75,85 | tr "," " "`;do
    cp S69L_transabyss_${x}/k${x}.transabyss.fa-final.fa S69L.TransABySS.k${x}.fa
done

rm -rf S69L_transabyss_*
Status

Exit: 1 (FAILED) Attempts: 1 (action: FINISH)

**Comment by juadiegaitan** [comment]
Sorry Ramon, an update of the error:

Command error:
  Traceback (most recent call last):
    File "/home/xxxx/TransPi/condaEnv/env-9a1bd41ef2ac4d341bfff3fbe3a95182/bin/transabyss", line 18, in <module>
      from transabyss.adj_utils import has_edges
    File "/home/xxxx/TransPi/condaEnv/env-9a1bd41ef2ac4d341bfff3fbe3a95182/lib/python3.8/site-packages/transabyss/adj_utils.py", line 6, in <module>
      import igraph
    File "/home/xxxx/TransPi/condaEnv/env-9a1bd41ef2ac4d341bfff3fbe3a95182/lib/python3.8/site-packages/igraph/__init__.py", line 34, in <module>
      from igraph._igraph import *
  ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory

**Comment by rivera10** [comment]
Hello Juan,

By the look of the error, I see you are running the pipeline using individual conda environments per process (i.e. `-profile conda`). Is that correct? I have seen a couple of issues with single conda environments per process before. I will check how these can be solved. 

In the meantime, I will recommend creating a single conda environment to solve this issue. This is done for you by the precheck script. Then you will run TransPi using the `-profile conda --myConda` options. 

Let me know if you have any further issues. 

Best,
Ramon

P.S. I suggest pulling the repository again since I fixed some minor bugs.

**Comment by juadiegaitan** [comment]
Thank you Ramon for the feedback!
Just to confirm something. Do I need to change the PATH to Conda installation from precheck in the nextflow.config file?
Thanks and best wishes
Juan

**Comment by rivera10** [comment]
Hello, 
Each time you run the precheck script it will automatically add the PATH of the conda installation, BUSCO databases, etc. to the `nextflow.config`. You then need to change, if needed, the `nextflow.config` for the resources available on your system like CPUs and RAM. Anything let me know. 
Best, 
Ramon

**Comment by juadiegaitan** [comment]
Hi Ramon
All solved. Thanks for the detailed guidance also in the documents. It is running well now.
Best
Juan

**Comment by rivera10** [comment]
Great! Any other issues let me know. Best, Ramon
