### ISSUE TITLE
Getting done without running processes

### ISSUE THREAD

**Issue by vhfsantos** [PalMuc/TransPi#7]
Hi, Thank you for this amazing pipeline!

I tried to run the intire pipeline with the test dataset (`-profile conda,test`) and everything was ok. 

However, when I try to run with my data, it gets done after running only the first three processes:

![image](https://user-images.githubusercontent.com/38498789/110107938-4f0ad180-7d8a-11eb-9469-4f9092a93eb6.png)

I tried to run with `--onlyAsm` option as well, but it gets done without running any process:

![image](https://user-images.githubusercontent.com/38498789/110108243-af017800-7d8a-11eb-8fa2-3f2aa94583a7.png)

I also tested running with all different profiles and got the same error. 
Do you know what might be happening here?

Thanks in advance!

**Comment by rivera10** [comment]
Hello @vhfsantos, 

Can you share the command used to start the pipeline?  I see you are using conda, but I am not sure if it is with the TransPi environment (installed with the precheck) or with individual conda environments. Also, it looks that it could be an issue with the `--reads` option since it is starting but then stopping after the databases are created. Let me know.

Best,
Ramon

P.S. I suggest pulling the repository again since I fixed some minor bugs.

**Comment by vhfsantos** [comment]
Hello @rivera10 , thank you for your reply.

Here is the command line:

```
$ ./nextflow run TransPi.nf --all -profile conda --maxReadLen 101 --k 25,41,53,61 --reads '/home/vinicius/raw/*fastq.gz' --outdir 2021_TRANSPI-RESULTS
```
I also tried with:

```
$ ./nextflow run TransPi.nf --all -profile conda --myConda --maxReadLen 101 --k 25,41,53,61 --reads '/home/vinicius/raw/*fastq.gz' --outdir 2021_TRANSPI-RESULTS
```
But I got the same result.
I pulled the repo yesterday. Also, I am running everything inside the TransPi directory

Thanks,
Vinícius

**Comment by rivera10** [comment]
It seems the issue is in the way the `--reads` parameter is interpreted by nextflow while creating the channels using `fromFilePairs`. It accepts `R[1,2].fastq.gz` and not `*.fastq.gz`.

Try like this
```
./nextflow run TransPi.nf --all -profile conda --myConda --maxReadLen 101 --k 25,41,53,61 --reads '/home/vinicius/raw/*R[1,2].fastq.gz' --outdir 2021_TRANSPI-RESULTS
```

Let me know if this works

Best,
Ramon

**Comment by vhfsantos** [comment]
Oh, now it's running! :blush:  Thank you for your help!

Best,
Vinícius

**Comment by rivera10** [comment]
No worries. Anything let me know.
