### ISSUE TITLE
Error related to BUSCO

### ISSUE THREAD

**Issue by gushiro** [PalMuc/TransPi#9]
Hi there,
I am having problems installing TransPi with the "bash precheck_TransPi.sh" . The installation ended up in:

```
 -- Selecting BUSCO V4 database -- 


	 -- ERROR: Please make sure that file "busV4list.txt" is available. Please check requirements and rerun the pre-check --
```

Thanks in advance!

**Comment by rivera10** [comment]
Hello @gushiro,

You will get that error if you run the precheck and want to install the DBs in a different directory from where the repository was cloned. Thanks for reporting this. I'll work on a solution. 

In the meantime you can either run the precheck in the same directory where TransPi was cloned, or you can copy the `conf` directory (from TransPi directory) to the `PATH` where you want to install the DBs. 

Let me know if you have further issues.  

Best,
Ramon

**Comment by rivera10** [comment]
I fixed this on the dev branch. See [0011ce1 ](https://github.com/PalMuc/TransPi/commit/0011ce1390fae213696da893196d5cb19351e170). Let me know if you need further help.
